In [1]:
import arbor
import re

In [2]:
import pyNN.arbor as sim

In [3]:
from neuron import nrn

In [6]:
from pyNN.morphology import NeuroMLMorphology, load_morphology, uniform, random_section, dendrites, apical_dendrites, by_distance, dendrites, MorphologyFilter
from neuroml import Morphology, Segment, Point3DWithDiam as P

In [10]:
import numpy as np

In [11]:
soma = Segment(proximal=P(x=0, y=0, z=0, diameter=18.8),
               distal=P(x=18.8, y=0, z=0, diameter=18.8),
               name="soma", id=0)
dend = Segment(proximal=P(x=0, y=0, z=0, diameter=2),
               distal=P(x=-500, y=0, z=0, diameter=2),
               name="dendrite",
               parent=soma, id=1)
nu_morph = NeuroMLMorphology(Morphology(segments=(soma, dend)))

In [12]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [13]:
print({1: np.array([1, 2, 3, 4, 5])})

{1: array([1, 2, 3, 4, 5])}


In [15]:
np.append(np.array([1, 2, 3, 4, 5]), 6)

array([1, 2, 3, 4, 5, 6])

In [16]:
isinstance(arr, np.array)

TypeError: isinstance() arg 2 must be a type or tuple of types

In [17]:
np.append(np.array([]), 1)

array([1.])

In [21]:
np.append(np.array(1), 2)

array([1, 2])

In [18]:
for indx, nml_seg in enumerate(nu_morph.segments):
    print(indx, nml_seg)

0 <Segment|0|soma>
1 <Segment|1|dendrite>


In [19]:
import pyNN.morphology as pyNNmorph

In [20]:
pyNNmorph.SOMA

1

In [25]:
section_groups = {}
if 1 in section_groups.keys():
    print("yes")
else:
    print("no")

no


In [33]:
section_groups = {}
for indx, nml_seg in enumerate(nu_morph.segments):
    tag = 1 # get tag from nml_seg
    if tag not in section_groups.keys():
        section_groups.update({tag: np.array(indx)})
    else:
        section_groups[tag] = np.append(section_groups[tag], indx)

In [34]:
section_groups

{1: array([0, 1])}

In [35]:
nu_morph.section_groups

{}

In [32]:
kdr={"conductance_density": by_distance(dendrites(), lambda d: 0.05*d/200.0), "e_rev": -77.0}
#kdr["conductance_density"].selector(nu_morph)

In [36]:
nu_morph.segments

(<Segment|0|soma>, <Segment|1|dendrite>)

In [37]:
nu_morph.section_groups.update({1: np.array(0), 3: np.array(1)})

In [38]:
nu_morph.section_groups

{1: array(0), 3: array(1)}

In [40]:
kdr["conductance_density"]

In [39]:
kdr["conductance_density"].selector(nu_morph)

array([1])

In [43]:
ids = kdr["conductance_density"].selector(nu_morph)
for i in ids:
    #print(nu_morph.get_distance(i))
    print(i)

1


In [44]:
ids = kdr["conductance_density"].selector(nu_morph)
for i in ids:
    print(nu_morph.get_distance(i))

NotImplementedError: 

In [45]:
nu_morph.path_lengths(1)

NotImplementedError: 

In [46]:
sim.DCSource

AttributeError: module 'pyNN.arbor' has no attribute 'DCSource'

In [47]:
help(arbor.iclamp)

Help on class iclamp in module arbor._arbor:

class iclamp(pybind11_builtins.pybind11_object)
 |  A current clamp for injecting a DC or fixed frequency current governed by a piecewise linear envelope.
 |  
 |  Method resolution order:
 |      iclamp
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(...)
 |      __init__(*args, **kwargs)
 |      Overloaded function.
 |      
 |      1. __init__(self: arbor._arbor.iclamp, tstart: float, duration: float, current: float, *, frequency: float = 0, phase: float = 0) -> None
 |      
 |      Construct finite duration current clamp, constant amplitude
 |      
 |      2. __init__(self: arbor._arbor.iclamp, current: float, *, frequency: float = 0, phase: float = 0) -> None
 |      
 |      Construct constant amplitude current clamp
 |      
 |      3. __init__(self: arbor._arbor.iclamp, envelope: List[Tuple[float, float]], *, frequency: float = 0, phase: float = 0) -> None
 |      

In [48]:
x = {"a": 1, "b": 2, "c": 3}
for k, v in x.items():
    print(k, v)

a 1
b 2
c 3


In [60]:
y = np.array([1, 2, 3])

In [61]:
y.size

3

In [63]:
for i in y:
    print(i)

1
2
3


In [54]:
import pyNN.arbor as sim
sim.setup(timestep=0.025)

0

In [55]:
dc = sim.DCSource(amplitude=0.1, start=50.0, stop=150.0)

AttributeError: module 'pyNN.arbor' has no attribute 'DCSource'

In [56]:
import pyNN.neuron as sim2

In [58]:
dc = sim2.DCSource(amplitude=0.1, start=50.0, stop=150.0)

{'amplitude': <class 'float'>, 'start': <class 'float'>, 'stop': <class 'float'>}
{'amplitude': <class 'float'>, 'start': <class 'float'>, 'stop': <class 'float'>}
amplitude <larray: base_value=0.1 shape=(1,) dtype=<class 'float'>, operations=[]>
start <larray: base_value=50.0 shape=(1,) dtype=<class 'float'>, operations=[]>
stop <larray: base_value=150.0 shape=(1,) dtype=<class 'float'>, operations=[]>


In [75]:
dc.stop

150.0

In [65]:
class Foo(object):
    def __init__(self, a=0):
        self.x = a

In [66]:
cells = np.array([Foo(), Foo(1), Foo(2), Foo(3)])

In [67]:
for id in cells:
    print(id)

In [70]:
for id in cells[0:2]:
    id.x = id.x+1

In [71]:
cells[0].x

1

In [72]:
cells[1].x

2

In [73]:
region = "soma"
'"{}"'.format(region)

'"soma"'

In [77]:
'{}'.format(region)

'soma'

In [78]:
tst = {"a": 1, "b": 2, "c": 3, "d": 4}

In [79]:
for k, v in tst.items():
    print(k, v)

a 1
b 2
c 3
d 4


In [80]:
import neuroml

In [81]:
"s" is str

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
/tmp/ipykernel_104/1587389833.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  "s" is str


False

In [1]:
from pyNN.morphology import NeuroMLMorphology, load_morphology, uniform, random_section, dendrites, apical_dendrites, by_distance
from neuroml import Morphology, Segment, Point3DWithDiam as P
soma = Segment(proximal=P(x=0, y=0, z=0, diameter=18.8),
               distal=P(x=18.8, y=0, z=0, diameter=18.8),
               name="soma", id=0)
dend = Segment(proximal=P(x=0, y=0, z=0, diameter=2),
               distal=P(x=-500, y=0, z=0, diameter=2),
               name="dendrite",
               parent=soma, id=1)
nu_morph = NeuroMLMorphology(Morphology(segments=(soma, dend)))
import pyNN.arbor as sim
sim.setup(timestep=0.025)
cc = sim.MultiCompartmentNeuron.setup(
				label="MyCell",
				ion_channels={'pas': sim.PassiveLeak,
							  'na': sim.NaChannel,
							  'kdr': sim.KdrChannel},
				ionic_species={'na_ion': sim.NaIon,
							   'k_ion': sim.KIon})
mycell = cc(morphology=nu_morph,
			cm=1.0,
			Ra=500.0,
			na_ion = {"reversal_potential": 50.0},
			k_ion = {"reversal_potential": -77.0},
			pas={"conductance_density": uniform('all', 0.0003),
				"e_rev":-54.3},
			na={"conductance_density": uniform('soma', 0.120),
			   "e_rev": 50.0},
			kdr={"conductance_density": uniform('soma', 0.036),
				"e_rev": -77.0})

In [2]:
from pyNN.arbor.cells import ArborTemplate
mycell = ArborTemplate(morphology=nu_morph,
			cm=1.0,
			Ra=500.0,
			na_ion = {"reversal_potential": 50.0},
			k_ion = {"reversal_potential": -77.0},
			pas={"conductance_density": uniform('all', 0.0003),
				"e_rev":-54.3},
			na={"conductance_density": uniform('soma', 0.120),
			   "e_rev": 50.0},
			kdr={"conductance_density": uniform('soma', 0.036),
				"e_rev": -77.0})

0 None
1 <Segment|0|soma>


In [3]:
pyr_morph = load_morphology("oi15rpy4-1.CNG.swc", replace_axon=None)
mycell2 = ArborTemplate(morphology=pyr_morph,
			cm=1.0,
			Ra=500.0,
			na_ion = {"reversal_potential": 50.0},
			k_ion = {"reversal_potential": -77.0},
			pas={"conductance_density": uniform('all', 0.0003),
				"e_rev":-54.3},
			na={"conductance_density": uniform('soma', 0.120),
			   "e_rev": 50.0},
			kdr={"conductance_density": uniform('soma', 0.036),
				"e_rev": -77.0})

0 None
1 <None segment="0"/>

2 <None segment="0"/>

3 <None segment="3"/>



RuntimeError: invalid segment parent 3 for a segment tree of size 3

In [ ]:
for indx, nml_seg in enumerate(pyr_morph.segments):
    pass

In [ ]:
indx

In [ ]:
nml_seg.

In [ ]:
nml_seg.id, nml_seg.info, nml_seg.length, nml_seg.name, nml_seg.surface_area, nml_seg.volume

In [ ]:
for attr, value in nml_seg.__dict__.items():
        print(attr, value)

In [4]:
pyr_morph.section_groups

{2: array([ 1202,  1203,  1204, ..., 10956, 10957, 10958]),
 3: array([   3,    4,    5, ..., 1199, 1200, 1201]),
 4: array([10959, 10960, 10961, 10962, 10963, 10964, 10965, 10966, 10967,
        10968, 10969, 10970, 10971, 10972, 10973, 10974, 10975, 10976,
        10977, 10978, 10979, 10980, 10981, 10982, 10983, 10984, 10985,
        10986, 10987, 10988, 10989, 10990, 10991, 10992, 10993, 10994,
        10995, 10996, 10997, 10998, 10999, 11000, 11001, 11002, 11003,
        11004, 11005, 11006, 11007, 11008, 11009, 11010, 11011, 11012,
        11013, 11014, 11015, 11016, 11017, 11018, 11019, 11020, 11021,
        11022, 11023, 11024, 11025, 11026, 11027, 11028, 11029, 11030,
        11031, 11032, 11033, 11034, 11035, 11036, 11037, 11038, 11039,
        11040, 11041, 11042, 11043, 11044, 11045, 11046, 11047, 11048,
        11049, 11050, 11051, 11052, 11053, 11054, 11055, 11056, 11057,
        11058, 11059, 11060, 11061, 11062, 11063, 11064, 11065, 11066,
        11067, 11068, 11069, 11

In [5]:
11444 in pyr_morph.section_groups[4]

True

In [6]:
pyr_morph.segments[0]

<Segment|1|soma>

In [7]:
pyr_morph.segments[0].id

1

In [8]:
pyr_morph.segments[0].id in pyr_morph.section_groups[2]

False

In [9]:
for indx, nml_seg in enumerate(pyr_morph.segments):
    print(indx, nml_seg.parent)

0 None
1 <None segment="0"/>

2 <None segment="0"/>

3 <None segment="3"/>

4 <None segment="4"/>

5 <None segment="5"/>

6 <None segment="6"/>

7 <None segment="7"/>

8 <None segment="8"/>

9 <None segment="9"/>

10 <None segment="10"/>

11 <None segment="11"/>

12 <None segment="12"/>

13 <None segment="13"/>

14 <None segment="14"/>

15 <None segment="15"/>

16 <None segment="16"/>

17 <None segment="17"/>

18 <None segment="18"/>

19 <None segment="19"/>

20 <None segment="20"/>

21 <None segment="21"/>

22 <None segment="22"/>

23 <None segment="23"/>

24 <None segment="24"/>

25 <None segment="25"/>

26 <None segment="26"/>

27 <None segment="27"/>

28 <None segment="28"/>

29 <None segment="29"/>

30 <None segment="30"/>

31 <None segment="31"/>

32 <None segment="32"/>

33 <None segment="33"/>

34 <None segment="34"/>

35 <None segment="35"/>

36 <None segment="36"/>

37 <None segment="37"/>

38 <None segment="38"/>

39 <None segment="39"/>

40 <None segment="40"/>

41 <None se

704 <None segment="704"/>

705 <None segment="705"/>

706 <None segment="706"/>

707 <None segment="707"/>

708 <None segment="708"/>

709 <None segment="709"/>

710 <None segment="710"/>

711 <None segment="711"/>

712 <None segment="712"/>

713 <None segment="713"/>

714 <None segment="714"/>

715 <None segment="715"/>

716 <None segment="716"/>

717 <None segment="717"/>

718 <None segment="718"/>

719 <None segment="719"/>

720 <None segment="720"/>

721 <None segment="721"/>

722 <None segment="722"/>

723 <None segment="723"/>

724 <None segment="724"/>

725 <None segment="725"/>

726 <None segment="726"/>

727 <None segment="727"/>

728 <None segment="728"/>

729 <None segment="729"/>

730 <None segment="730"/>

731 <None segment="731"/>

732 <None segment="732"/>

733 <None segment="733"/>

734 <None segment="734"/>

735 <None segment="735"/>

736 <None segment="736"/>

737 <None segment="737"/>

738 <None segment="738"/>

739 <None segment="739"/>

740 <None segment="740"/>

7

1440 <None segment="1440"/>

1441 <None segment="1441"/>

1442 <None segment="1442"/>

1443 <None segment="1443"/>

1444 <None segment="1444"/>

1445 <None segment="1445"/>

1446 <None segment="1446"/>

1447 <None segment="1447"/>

1448 <None segment="1448"/>

1449 <None segment="1449"/>

1450 <None segment="1217"/>

1451 <None segment="1451"/>

1452 <None segment="1452"/>

1453 <None segment="1453"/>

1454 <None segment="1454"/>

1455 <None segment="1455"/>

1456 <None segment="1456"/>

1457 <None segment="1457"/>

1458 <None segment="1458"/>

1459 <None segment="1459"/>

1460 <None segment="1460"/>

1461 <None segment="1461"/>

1462 <None segment="1462"/>

1463 <None segment="1463"/>

1464 <None segment="1464"/>

1465 <None segment="1465"/>

1466 <None segment="1466"/>

1467 <None segment="1467"/>

1468 <None segment="1468"/>

1469 <None segment="1467"/>

1470 <None segment="1470"/>

1471 <None segment="1470"/>

1472 <None segment="1472"/>

1473 <None segment="1473"/>

1474 <None seg

1986 <None segment="1986"/>

1987 <None segment="1987"/>

1988 <None segment="1988"/>

1989 <None segment="1989"/>

1990 <None segment="1990"/>

1991 <None segment="1991"/>

1992 <None segment="1992"/>

1993 <None segment="1993"/>

1994 <None segment="1994"/>

1995 <None segment="1995"/>

1996 <None segment="1996"/>

1997 <None segment="1997"/>

1998 <None segment="1998"/>

1999 <None segment="1999"/>

2000 <None segment="2000"/>

2001 <None segment="2001"/>

2002 <None segment="2002"/>

2003 <None segment="2003"/>

2004 <None segment="2004"/>

2005 <None segment="2005"/>

2006 <None segment="2006"/>

2007 <None segment="2007"/>

2008 <None segment="2008"/>

2009 <None segment="2009"/>

2010 <None segment="2010"/>

2011 <None segment="2011"/>

2012 <None segment="2012"/>

2013 <None segment="2013"/>

2014 <None segment="2014"/>

2015 <None segment="2015"/>

2016 <None segment="2016"/>

2017 <None segment="2017"/>

2018 <None segment="2018"/>

2019 <None segment="2019"/>

2020 <None seg

2619 <None segment="2619"/>

2620 <None segment="2184"/>

2621 <None segment="2621"/>

2622 <None segment="2622"/>

2623 <None segment="2623"/>

2624 <None segment="2624"/>

2625 <None segment="2625"/>

2626 <None segment="2626"/>

2627 <None segment="2627"/>

2628 <None segment="2628"/>

2629 <None segment="2629"/>

2630 <None segment="2630"/>

2631 <None segment="2631"/>

2632 <None segment="2632"/>

2633 <None segment="2633"/>

2634 <None segment="2634"/>

2635 <None segment="2635"/>

2636 <None segment="2636"/>

2637 <None segment="2637"/>

2638 <None segment="2638"/>

2639 <None segment="2639"/>

2640 <None segment="2640"/>

2641 <None segment="2641"/>

2642 <None segment="2642"/>

2643 <None segment="2643"/>

2644 <None segment="2644"/>

2645 <None segment="2645"/>

2646 <None segment="2646"/>

2647 <None segment="2647"/>

2648 <None segment="2648"/>

2649 <None segment="2649"/>

2650 <None segment="2650"/>

2651 <None segment="2651"/>

2652 <None segment="2652"/>

2653 <None seg

3305 <None segment="3305"/>

3306 <None segment="3306"/>

3307 <None segment="3307"/>

3308 <None segment="3308"/>

3309 <None segment="3309"/>

3310 <None segment="3310"/>

3311 <None segment="3311"/>

3312 <None segment="3312"/>

3313 <None segment="3313"/>

3314 <None segment="3314"/>

3315 <None segment="3315"/>

3316 <None segment="3316"/>

3317 <None segment="3317"/>

3318 <None segment="3318"/>

3319 <None segment="3319"/>

3320 <None segment="3320"/>

3321 <None segment="3321"/>

3322 <None segment="3322"/>

3323 <None segment="3323"/>

3324 <None segment="3324"/>

3325 <None segment="3325"/>

3326 <None segment="3326"/>

3327 <None segment="3327"/>

3328 <None segment="3328"/>

3329 <None segment="3329"/>

3330 <None segment="3330"/>

3331 <None segment="3331"/>

3332 <None segment="3332"/>

3333 <None segment="3333"/>

3334 <None segment="3334"/>

3335 <None segment="3335"/>

3336 <None segment="3336"/>

3337 <None segment="3337"/>

3338 <None segment="3338"/>

3339 <None seg

3953 <None segment="3953"/>

3954 <None segment="3954"/>

3955 <None segment="3955"/>

3956 <None segment="3956"/>

3957 <None segment="3957"/>

3958 <None segment="3958"/>

3959 <None segment="3959"/>

3960 <None segment="3960"/>

3961 <None segment="3961"/>

3962 <None segment="3962"/>

3963 <None segment="3963"/>

3964 <None segment="3964"/>

3965 <None segment="3965"/>

3966 <None segment="3966"/>

3967 <None segment="3967"/>

3968 <None segment="3968"/>

3969 <None segment="3969"/>

3970 <None segment="3970"/>

3971 <None segment="3971"/>

3972 <None segment="3972"/>

3973 <None segment="3973"/>

3974 <None segment="3974"/>

3975 <None segment="3975"/>

3976 <None segment="3976"/>

3977 <None segment="3977"/>

3978 <None segment="3978"/>

3979 <None segment="3979"/>

3980 <None segment="3980"/>

3981 <None segment="3981"/>

3982 <None segment="3982"/>

3983 <None segment="3983"/>

3984 <None segment="3984"/>

3985 <None segment="3985"/>

3986 <None segment="3986"/>

3987 <None seg

4673 <None segment="4673"/>

4674 <None segment="4674"/>

4675 <None segment="4675"/>

4676 <None segment="4676"/>

4677 <None segment="4677"/>

4678 <None segment="4678"/>

4679 <None segment="4679"/>

4680 <None segment="4680"/>

4681 <None segment="4681"/>

4682 <None segment="4658"/>

4683 <None segment="4683"/>

4684 <None segment="4684"/>

4685 <None segment="4685"/>

4686 <None segment="4686"/>

4687 <None segment="4687"/>

4688 <None segment="4688"/>

4689 <None segment="4687"/>

4690 <None segment="4643"/>

4691 <None segment="4691"/>

4692 <None segment="4692"/>

4693 <None segment="4693"/>

4694 <None segment="4694"/>

4695 <None segment="4695"/>

4696 <None segment="4696"/>

4697 <None segment="4697"/>

4698 <None segment="4698"/>

4699 <None segment="4699"/>

4700 <None segment="4700"/>

4701 <None segment="4701"/>

4702 <None segment="4702"/>

4703 <None segment="4703"/>

4704 <None segment="4704"/>

4705 <None segment="4705"/>

4706 <None segment="4706"/>

4707 <None seg

5452 <None segment="5452"/>

5453 <None segment="5453"/>

5454 <None segment="5454"/>

5455 <None segment="5455"/>

5456 <None segment="5456"/>

5457 <None segment="5457"/>

5458 <None segment="5458"/>

5459 <None segment="5459"/>

5460 <None segment="5460"/>

5461 <None segment="5461"/>

5462 <None segment="5462"/>

5463 <None segment="5463"/>

5464 <None segment="5464"/>

5465 <None segment="5465"/>

5466 <None segment="5466"/>

5467 <None segment="5467"/>

5468 <None segment="5468"/>

5469 <None segment="5469"/>

5470 <None segment="5470"/>

5471 <None segment="5471"/>

5472 <None segment="5472"/>

5473 <None segment="5473"/>

5474 <None segment="5474"/>

5475 <None segment="5475"/>

5476 <None segment="5476"/>

5477 <None segment="5477"/>

5478 <None segment="5478"/>

5479 <None segment="5479"/>

5480 <None segment="5480"/>

5481 <None segment="5481"/>

5482 <None segment="5482"/>

5483 <None segment="5483"/>

5484 <None segment="5484"/>

5485 <None segment="5485"/>

5486 <None seg

6202 <None segment="6202"/>

6203 <None segment="6203"/>

6204 <None segment="6204"/>

6205 <None segment="6205"/>

6206 <None segment="6206"/>

6207 <None segment="6207"/>

6208 <None segment="6208"/>

6209 <None segment="6209"/>

6210 <None segment="6210"/>

6211 <None segment="6211"/>

6212 <None segment="6212"/>

6213 <None segment="6213"/>

6214 <None segment="6214"/>

6215 <None segment="6215"/>

6216 <None segment="6216"/>

6217 <None segment="6217"/>

6218 <None segment="6218"/>

6219 <None segment="6219"/>

6220 <None segment="6220"/>

6221 <None segment="6221"/>

6222 <None segment="6222"/>

6223 <None segment="6223"/>

6224 <None segment="6224"/>

6225 <None segment="6225"/>

6226 <None segment="6226"/>

6227 <None segment="6227"/>

6228 <None segment="5377"/>

6229 <None segment="6229"/>

6230 <None segment="6230"/>

6231 <None segment="6231"/>

6232 <None segment="6232"/>

6233 <None segment="6233"/>

6234 <None segment="6234"/>

6235 <None segment="6235"/>

6236 <None seg

6781 <None segment="6781"/>

6782 <None segment="6782"/>

6783 <None segment="6783"/>

6784 <None segment="6784"/>

6785 <None segment="6785"/>

6786 <None segment="6786"/>

6787 <None segment="6787"/>

6788 <None segment="6788"/>

6789 <None segment="6789"/>

6790 <None segment="6790"/>

6791 <None segment="6740"/>

6792 <None segment="6792"/>

6793 <None segment="6793"/>

6794 <None segment="6794"/>

6795 <None segment="6795"/>

6796 <None segment="6796"/>

6797 <None segment="6797"/>

6798 <None segment="6798"/>

6799 <None segment="6799"/>

6800 <None segment="6800"/>

6801 <None segment="6801"/>

6802 <None segment="6802"/>

6803 <None segment="6803"/>

6804 <None segment="6804"/>

6805 <None segment="6805"/>

6806 <None segment="6806"/>

6807 <None segment="6807"/>

6808 <None segment="6808"/>

6809 <None segment="6809"/>

6810 <None segment="6810"/>

6811 <None segment="6811"/>

6812 <None segment="6812"/>

6813 <None segment="6813"/>

6814 <None segment="6814"/>

6815 <None seg

7368 <None segment="7368"/>

7369 <None segment="7369"/>

7370 <None segment="7370"/>

7371 <None segment="7371"/>

7372 <None segment="7372"/>

7373 <None segment="7373"/>

7374 <None segment="7374"/>

7375 <None segment="7375"/>

7376 <None segment="7376"/>

7377 <None segment="7377"/>

7378 <None segment="7378"/>

7379 <None segment="7379"/>

7380 <None segment="7380"/>

7381 <None segment="7381"/>

7382 <None segment="7382"/>

7383 <None segment="7383"/>

7384 <None segment="7384"/>

7385 <None segment="7385"/>

7386 <None segment="7386"/>

7387 <None segment="7387"/>

7388 <None segment="7388"/>

7389 <None segment="7389"/>

7390 <None segment="7390"/>

7391 <None segment="7391"/>

7392 <None segment="7392"/>

7393 <None segment="7393"/>

7394 <None segment="7379"/>

7395 <None segment="7395"/>

7396 <None segment="7396"/>

7397 <None segment="7397"/>

7398 <None segment="7398"/>

7399 <None segment="7399"/>

7400 <None segment="7400"/>

7401 <None segment="7401"/>

7402 <None seg


7911 <None segment="7911"/>

7912 <None segment="7912"/>

7913 <None segment="7913"/>

7914 <None segment="7914"/>

7915 <None segment="7915"/>

7916 <None segment="7916"/>

7917 <None segment="7917"/>

7918 <None segment="7918"/>

7919 <None segment="7919"/>

7920 <None segment="7920"/>

7921 <None segment="7921"/>

7922 <None segment="7922"/>

7923 <None segment="7923"/>

7924 <None segment="7924"/>

7925 <None segment="7925"/>

7926 <None segment="7926"/>

7927 <None segment="7927"/>

7928 <None segment="7928"/>

7929 <None segment="7929"/>

7930 <None segment="7930"/>

7931 <None segment="7931"/>

7932 <None segment="7932"/>

7933 <None segment="7933"/>

7934 <None segment="7934"/>

7935 <None segment="7935"/>

7936 <None segment="7936"/>

7937 <None segment="7937"/>

7938 <None segment="7938"/>

7939 <None segment="7939"/>

7940 <None segment="7940"/>

7941 <None segment="7941"/>

7942 <None segment="7942"/>

7943 <None segment="7943"/>

7944 <None segment="7944"/>

7945 <None se

8510 <None segment="8510"/>

8511 <None segment="8511"/>

8512 <None segment="8512"/>

8513 <None segment="8513"/>

8514 <None segment="8514"/>

8515 <None segment="8515"/>

8516 <None segment="8516"/>

8517 <None segment="8517"/>

8518 <None segment="8518"/>

8519 <None segment="8519"/>

8520 <None segment="8520"/>

8521 <None segment="8521"/>

8522 <None segment="8522"/>

8523 <None segment="8523"/>

8524 <None segment="8524"/>

8525 <None segment="8525"/>

8526 <None segment="8526"/>

8527 <None segment="8527"/>

8528 <None segment="8528"/>

8529 <None segment="8529"/>

8530 <None segment="8530"/>

8531 <None segment="8531"/>

8532 <None segment="8532"/>

8533 <None segment="8533"/>

8534 <None segment="8534"/>

8535 <None segment="8535"/>

8536 <None segment="8536"/>

8537 <None segment="8537"/>

8538 <None segment="8538"/>

8539 <None segment="8539"/>

8540 <None segment="8540"/>

8541 <None segment="8541"/>

8542 <None segment="8542"/>

8543 <None segment="8543"/>

8544 <None seg

9296 <None segment="9296"/>

9297 <None segment="9297"/>

9298 <None segment="9298"/>

9299 <None segment="9299"/>

9300 <None segment="9300"/>

9301 <None segment="9301"/>

9302 <None segment="9302"/>

9303 <None segment="9303"/>

9304 <None segment="9304"/>

9305 <None segment="9305"/>

9306 <None segment="9306"/>

9307 <None segment="9307"/>

9308 <None segment="9308"/>

9309 <None segment="9309"/>

9310 <None segment="9310"/>

9311 <None segment="9311"/>

9312 <None segment="9312"/>

9313 <None segment="9313"/>

9314 <None segment="9314"/>

9315 <None segment="9315"/>

9316 <None segment="9316"/>

9317 <None segment="9317"/>

9318 <None segment="9318"/>

9319 <None segment="9319"/>

9320 <None segment="9320"/>

9321 <None segment="9321"/>

9322 <None segment="9322"/>

9323 <None segment="9323"/>

9324 <None segment="9324"/>

9325 <None segment="9325"/>

9326 <None segment="9326"/>

9327 <None segment="9327"/>

9328 <None segment="9328"/>

9329 <None segment="9329"/>

9330 <None seg

9799 <None segment="9799"/>

9800 <None segment="9800"/>

9801 <None segment="9801"/>

9802 <None segment="9802"/>

9803 <None segment="9803"/>

9804 <None segment="9804"/>

9805 <None segment="9805"/>

9806 <None segment="9806"/>

9807 <None segment="9807"/>

9808 <None segment="9808"/>

9809 <None segment="9809"/>

9810 <None segment="9810"/>

9811 <None segment="9811"/>

9812 <None segment="9812"/>

9813 <None segment="9813"/>

9814 <None segment="9814"/>

9815 <None segment="9815"/>

9816 <None segment="9816"/>

9817 <None segment="9817"/>

9818 <None segment="9818"/>

9819 <None segment="9819"/>

9820 <None segment="9820"/>

9821 <None segment="9821"/>

9822 <None segment="9822"/>

9823 <None segment="9823"/>

9824 <None segment="9824"/>

9825 <None segment="9825"/>

9826 <None segment="9826"/>

9827 <None segment="9827"/>

9828 <None segment="9828"/>

9829 <None segment="9829"/>

9830 <None segment="9830"/>

9831 <None segment="9831"/>

9832 <None segment="9832"/>

9833 <None seg

10621 <None segment="10621"/>

10622 <None segment="10622"/>

10623 <None segment="10623"/>

10624 <None segment="10624"/>

10625 <None segment="10625"/>

10626 <None segment="10626"/>

10627 <None segment="10627"/>

10628 <None segment="10628"/>

10629 <None segment="10629"/>

10630 <None segment="10630"/>

10631 <None segment="10631"/>

10632 <None segment="10632"/>

10633 <None segment="10633"/>

10634 <None segment="10634"/>

10635 <None segment="10635"/>

10636 <None segment="10636"/>

10637 <None segment="10637"/>

10638 <None segment="10638"/>

10639 <None segment="10639"/>

10640 <None segment="10640"/>

10641 <None segment="10641"/>

10642 <None segment="10642"/>

10643 <None segment="10643"/>

10644 <None segment="10644"/>

10645 <None segment="10645"/>

10646 <None segment="10646"/>

10647 <None segment="10628"/>

10648 <None segment="10648"/>

10649 <None segment="10649"/>

10650 <None segment="10650"/>

10651 <None segment="10651"/>

10652 <None segment="10652"/>

10653 <N

11271 <None segment="11271"/>

11272 <None segment="11235"/>

11273 <None segment="11273"/>

11274 <None segment="11274"/>

11275 <None segment="11275"/>

11276 <None segment="11276"/>

11277 <None segment="11277"/>

11278 <None segment="11278"/>

11279 <None segment="11279"/>

11280 <None segment="11280"/>

11281 <None segment="11281"/>

11282 <None segment="11282"/>

11283 <None segment="11283"/>

11284 <None segment="11284"/>

11285 <None segment="11285"/>

11286 <None segment="11286"/>

11287 <None segment="11287"/>

11288 <None segment="11288"/>

11289 <None segment="11289"/>

11290 <None segment="11290"/>

11291 <None segment="11291"/>

11292 <None segment="11292"/>

11293 <None segment="11293"/>

11294 <None segment="11294"/>

11295 <None segment="11295"/>

11296 <None segment="11296"/>

11297 <None segment="11297"/>

11298 <None segment="11298"/>

11299 <None segment="11299"/>

11300 <None segment="11300"/>

11301 <None segment="11301"/>

11302 <None segment="11302"/>

11303 <N

In [10]:
pyr_morph.segments[0].parent

In [16]:
pyr_morph.segments[1].parent

In [17]:
help(pyr_morph.segments[1].parent)

Help on SegmentParent in module neuroml.nml.nml object:

class SegmentParent(GeneratedsSuper)
 |  SegmentParent(segments=None, fraction_along='1', gds_collector_=None, **kwargs_)
 |  
 |  Method resolution order:
 |      SegmentParent
 |      GeneratedsSuper
 |      GeneratedsSuperSuper
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __init__(self, segments=None, fraction_along='1', gds_collector_=None, **kwargs_)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  build(self, node, gds_collector_=None)
 |  
 |  export(self, outfile, level, namespaceprefix_='', namespacedef_='', name_='SegmentParent', pretty_print=True)
 |  
 |  validate_NonNegativeInteger(self, value)
 |  
 |  validate_ZeroToOne(self, value)
 |  
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |  
 |  factory(*args_, **kwargs_)
 |  
 |  -------------------------

In [18]:
pyr_morph.segments[1].parent

In [19]:
print(pyr_morph.segments[1].parent)

<None segment="0"/>



In [20]:
type(pyr_morph.segments[1].parent)

neuroml.nml.nml.SegmentParent

In [21]:
M = pyr_morph._morphology

In [22]:
M.vertices[0]

array([ 0.   ,  0.   ,  0.   , 10.321], dtype=float32)

In [23]:
for attr, value in M.__dict__.items():
        print(attr, value)

gds_collector_ None
gds_elementtree_node_ None
original_tagname_ None
parent_object_ None
ns_prefix_ None
neuro_lex_id None
neuro_lex_id_nsprefix_ None
extensiontype_ None
id None
id_nsprefix_ None
metaid None
metaid_nsprefix_ None
notes None
notes_nsprefix_ None
properties []
properties_nsprefix_ None
annotation None
annotation_nsprefix_ None
segments <neuroml.arraymorph.SegmentList object at 0x7fa2141ba700>
segments_nsprefix_ None
segment_groups []
segment_groups_nsprefix_ None
connectivity [   -1     0     0 ... 11441 11442 11443]
vertices [[ 0.0000e+00  0.0000e+00  0.0000e+00  1.0321e+01]
 [ 7.9900e+00  6.3000e+00 -1.6600e+00  1.0321e+01]
 [-7.9900e+00 -6.3000e+00  1.6600e+00  1.0321e+01]
 ...
 [ 2.3403e+02 -8.4668e+02 -5.4600e+00  2.2000e-01]
 [ 2.3480e+02 -8.5343e+02 -4.8100e+00  2.2000e-01]
 [ 2.3845e+02 -8.6592e+02 -5.8700e+00  2.2000e-01]]
physical_mask [False False False ... False False False]
node_types [1 1 1 ... 4 4 4]
fractions_along [0 0 0 ... 0 0 0]


In [24]:
vertex = M.vertices[0]
parent_index = M.connectivity[0]
parent = M.vertices[parent_index]

In [25]:
for v in (vertex, parent):
    x, y, z, d = v
    print(v)

[ 0.     0.     0.    10.321]
[ 2.3845e+02 -8.6592e+02 -5.8700e+00  2.2000e-01]


In [26]:
x

238.45

In [27]:
vertex

array([ 0.   ,  0.   ,  0.   , 10.321], dtype=float32)

In [28]:
parent

array([ 2.3845e+02, -8.6592e+02, -5.8700e+00,  2.2000e-01], dtype=float32)

In [29]:
parent_index

-1

In [30]:
len(M.vertices), len(M.connectivity), len(M.segments)

(11445, 11445, 11444)

In [36]:
M.connectivity[5]

4

In [40]:
len(pyr_morph.segments)

11444

In [41]:
len(pyr_morph._morphology)

11445

In [42]:
len(M.vertices)

11445

In [39]:
pyr_morph.segments[0].proximal

(7.989999771118164, 6.300000190734863, -1.659999966621399), diam 10.321000099182129um

In [44]:
M.vertices[1]

array([ 7.99 ,  6.3  , -1.66 , 10.321], dtype=float32)

In [54]:
len(pyr_morph.segments)

11444

In [60]:
for i in range(11440,11444):  # len(pyr_morph.segments)
    print(pyr_morph.segments[i].proximal)
    print(M.vertices[i+1])
    print(M.connectivity[i+1])
    print(i)

(232.52999877929688, -839.1799926757812, -3.799999952316284), diam 0.2199999988079071um
[ 2.3253e+02 -8.3918e+02 -3.8000e+00  2.2000e-01]
11440
11440
(234.02999877929688, -846.6799926757812, -5.460000038146973), diam 0.2199999988079071um
[ 2.3403e+02 -8.4668e+02 -5.4600e+00  2.2000e-01]
11441
11441
(234.8000030517578, -853.4299926757812, -4.809999942779541), diam 0.2199999988079071um
[ 2.3480e+02 -8.5343e+02 -4.8100e+00  2.2000e-01]
11442
11442
(238.4499969482422, -865.9199829101562, -5.869999885559082), diam 0.2199999988079071um
[ 2.3845e+02 -8.6592e+02 -5.8700e+00  2.2000e-01]
11443
11443


In [63]:
M.connectivity[11444]

11443

In [46]:
pyr_morph.segments[0].proximal.x == M.vertices[1][0]

True

In [47]:
i = 0
seg = pyr_morph.segments[i]
xyzd = [seg.proximal.x, seg.proximal.y, seg.proximal.z, seg.proximal.diameter]
xyzd == M.vertices[i+1]

array([ True,  True,  True,  True])

In [49]:
import numpy as np

In [50]:
np.all(xyzd == M.vertices[i+1])

True

In [52]:
np.all(np.array([True,False,True]))

False

In [78]:
print(len(pyr_morph.segments), len(M.vertices))
start = 1 # 11440
stop = 100 # 11444
for i in range(start, stop):  # len(pyr_morph.segments)
    seg = pyr_morph.segments[i]
    xyzd = [seg.proximal.x, seg.proximal.y, seg.proximal.z, seg.proximal.diameter]
    #print(i, np.all(xyzd == M.vertices[i+1]))
    print(i, np.all(xyzd == M.vertices[i+1]), [seg.parent.segments, M.connectivity[i+1]])

11444 11445
1 True [0, 0]
2 True [0, 0]
3 True [3, 3]
4 True [4, 4]
5 True [5, 5]
6 True [6, 6]
7 True [7, 7]
8 True [8, 8]
9 True [9, 9]
10 True [10, 10]
11 True [11, 11]
12 True [12, 12]
13 True [13, 13]
14 True [14, 14]
15 True [15, 15]
16 True [16, 16]
17 True [17, 17]
18 True [18, 18]
19 True [19, 19]
20 True [20, 20]
21 True [21, 21]
22 True [22, 22]
23 True [23, 23]
24 True [24, 24]
25 True [25, 25]
26 True [26, 26]
27 True [27, 27]
28 True [28, 28]
29 True [29, 29]
30 True [30, 30]
31 True [31, 31]
32 True [32, 32]
33 True [33, 33]
34 True [34, 34]
35 True [35, 35]
36 True [36, 36]
37 True [37, 37]
38 True [38, 38]
39 True [39, 39]
40 True [40, 40]
41 True [41, 41]
42 True [42, 42]
43 True [43, 43]
44 True [44, 44]
45 True [45, 45]
46 True [8, 8]
47 True [47, 47]
48 True [48, 48]
49 True [49, 49]
50 True [50, 50]
51 True [51, 51]
52 True [52, 52]
53 True [53, 53]
54 True [54, 54]
55 True [55, 55]
56 True [56, 56]
57 True [57, 57]
58 True [58, 58]
59 True [59, 59]
60 True [60, 6

In [76]:
for i in range(1, len(pyr_morph.segments)):
    seg = pyr_morph.segments[i]
    xyzd = [seg.proximal.x, seg.proximal.y, seg.proximal.z, seg.proximal.diameter]
    yes_no1 = np.all(xyzd == M.vertices[i+1])
    yes_no2 = seg.parent.segments == M.connectivity[i+1]
    if yes_no1 is not yes_no2:
        print("false")

In [79]:
yes_no1 and yes_no2 is True

False

In [84]:
yes_no1

True

In [86]:
bool(yes_no1)

True

In [88]:
yes_no1 is True

False

In [89]:
bool(yes_no1) is True

True

In [90]:
bool(yes_no1) and bool(yes_no2) is True

True

In [48]:
for attr, value in pyr_morph.segments[0].__dict__.items():
        print(attr, value)

gds_collector_ None
gds_elementtree_node_ None
original_tagname_ None
parent_object_ None
ns_prefix_ None
neuro_lex_id None
neuro_lex_id_nsprefix_ None
extensiontype_ None
id 1
id_nsprefix_ None
name soma
name_nsprefix_ None
parent None
parent_nsprefix_ None
proximal (7.989999771118164, 6.300000190734863, -1.659999966621399), diam 10.321000099182129um
proximal_nsprefix_ None
distal (0.0, 0.0, 0.0), diam 10.321000099182129um
distal_nsprefix_ None


In [49]:
pyr_morph.segments[0].id

1

In [50]:
pyr_morph.segments[0].proximal

(7.989999771118164, 6.300000190734863, -1.659999966621399), diam 10.321000099182129um

In [51]:
pyr_morph.segments[0].distal

(0.0, 0.0, 0.0), diam 10.321000099182129um

In [53]:
type(pyr_morph.segments[0].proximal)

neuroml.nml.nml.Point3DWithDiam

In [54]:
x, y, z , d = pyr_morph.segments[0].proximal

TypeError: cannot unpack non-iterable Point3DWithDiam object

In [78]:
len(pyr_morph.segments)

11444

In [56]:
pyr_morph.segments[0].proximal.x, pyr_morph.segments[0].proximal.y, pyr_morph.segments[0].proximal.z

(7.989999771118164, 6.300000190734863, -1.659999966621399)

In [59]:
pyr_morph.segments[0].proximal.diameter

10.321000099182129

In [79]:
pyr_morph.segments[0].proximal.x, pyr_morph.segments[0].proximal.y, pyr_morph.segments[0].proximal.z, pyr_morph.segments[0].proximal.diameter

(7.989999771118164, 6.300000190734863, -1.659999966621399, 10.321000099182129)

In [60]:
for attr, value in pyr_morph.segments[1].__dict__.items():
        print(attr, value)

gds_collector_ None
gds_elementtree_node_ None
original_tagname_ None
parent_object_ None
ns_prefix_ None
neuro_lex_id None
neuro_lex_id_nsprefix_ None
extensiontype_ None
id 2
id_nsprefix_ None
name soma
name_nsprefix_ None
parent <None segment="0"/>

parent_nsprefix_ None
proximal (-7.989999771118164, -6.300000190734863, 1.659999966621399), diam 10.321000099182129um
proximal_nsprefix_ None
distal (0.0, 0.0, 0.0), diam 10.321000099182129um
distal_nsprefix_ None


In [80]:
pyr_morph.segments[1].parent

In [81]:
type(pyr_morph.segments[1].parent)

neuroml.nml.nml.SegmentParent

In [82]:
print(pyr_morph.segments[1].parent)

<None segment="0"/>



In [83]:
pyr_morph.segments[1].parent.segments

0

In [62]:
type(pyr_morph.segments[0])

neuroml.nml.nml.Segment

In [64]:
help(pyr_morph.segments[0])

Help on Segment in module neuroml.nml.nml object:

class Segment(BaseNonNegativeIntegerId)
 |  Segment(neuro_lex_id=None, id=None, name=None, parent=None, proximal=None, distal=None, gds_collector_=None, **kwargs_)
 |  
 |  Segment -- A segment defines the smallest unit within a possibly branching structure (  **morphology**  ), such as a dendrite or axon. Its **id**  should be a nonnegative integer ( usually soma/root = 0 ). Its end points are given by the  **proximal**  and  **distal**  points. The  **proximal**  point can be omitted, usually because it is the same as a point on the  **parent**  segment, see  **proximal**  for details.  **parent**  specifies the parent segment. The first segment of a  **cell**  ( with no  **parent**  ) usually represents the soma. The shape is normally a cylinder ( radii of the  **proximal**  and  **distal**  equal, but positions different ) or a conical frustum ( radii and positions different ). If the x, y, x positions of the  **proximal**  and  **

In [67]:
pyr_morph.segments[0].length, pyr_morph.segments[0].surface_area, pyr_morph.segments[0].volume

(10.309495556762739, 334.2789818423314, 862.5233511873008)

In [72]:
pyr_morph.segments[0].parent_nsprefix_ 

In [73]:
print(pyr_morph.segments[0].parent_nsprefix_ )

None


In [77]:
for attr, value in pyr_morph.segments[11443].__dict__.items():
        print(attr, value)

gds_collector_ None
gds_elementtree_node_ None
original_tagname_ None
parent_object_ None
ns_prefix_ None
neuro_lex_id None
neuro_lex_id_nsprefix_ None
extensiontype_ None
id 11444
id_nsprefix_ None
name apical_dendrite
name_nsprefix_ None
parent <None segment="11443"/>

parent_nsprefix_ None
proximal (238.4499969482422, -865.9199829101562, -5.869999885559082), diam 0.2199999988079071um
proximal_nsprefix_ None
distal (234.8000030517578, -853.4299926757812, -4.809999942779541), diam 0.2199999988079071um
distal_nsprefix_ None


In [84]:
pyr_morph.segments[11443].parent.segments

11443

In [85]:
pyr_morph.segments[11443].parent.id

AttributeError: 'SegmentParent' object has no attribute 'id'

In [86]:
pyr_morph.segments[11443].parent.id = pyr_morph.segments[11443].parent.segments

In [87]:
pyr_morph.segments[11443].parent.id

11443

In [ ]:
for i in range(1, len(pyr_morph.segments)):
    print(pyr_morph.segments[i].parent.segments)